MERGE INTO ratings (rating_id, rating_name) VALUES (1, 'G');
MERGE INTO ratings (rating_id, rating_name) VALUES (2, 'PG');
MERGE INTO ratings (rating_id, rating_name) VALUES (3, 'PG-13');
MERGE INTO ratings (rating_id, rating_name) VALUES (4, 'R');
MERGE INTO ratings (rating_id, rating_name) VALUES (5, 'NC-17');

MERGE INTO genres (genre_id, genre) VALUES (1, 'Action');
MERGE INTO genres (genre_id, genre) VALUES (2, 'Adventure');
MERGE INTO genres (genre_id, genre) VALUES (3, 'Comedy');
MERGE INTO genres (genre_id, genre) VALUES (4, 'Drama');
MERGE INTO genres (genre_id, genre) VALUES (5, 'Fantasy');
MERGE INTO genres (genre_id, genre) VALUES (6, 'Horror');
MERGE INTO genres (genre_id, genre) VALUES (7, 'Mystery');
MERGE INTO genres (genre_id, genre) VALUES (8, 'Romance');
MERGE INTO genres (genre_id, genre) VALUES (9, 'Science Fiction');
MERGE INTO genres (genre_id, genre) VALUES (10, 'Thriller');
MERGE INTO genres (genre_id, genre) VALUES (11, 'Animation');
MERGE INTO genres (genre_id, genre) VALUES (12, 'Documentary');
MERGE INTO genres (genre_id, genre) VALUES (13, 'Musical');
MERGE INTO genres (genre_id, genre) VALUES (14, 'Western');
MERGE INTO genres (genre_id, genre) VALUES (15, 'Historical');
MERGE INTO genres (genre_id, genre) VALUES (16, 'Sports');
MERGE INTO genres (genre_id, genre) VALUES (17, 'Superhero');
MERGE INTO genres (genre_id, genre) VALUES (18, 'Family');
MERGE INTO genres (genre_id, genre) VALUES (19, 'War');
MERGE INTO genres (genre_id, genre) VALUES (20, 'Crime');